plugins:
  cakeday_enabled:
    default: true
    client: true
  cakeday_emoji:
    default: 'cake'
    client: true
  its_your_birthday_enabled:
    default: true
    client: true
  its_your_birthday_emoji:
    default: 'birthday'
    client: true
